version: 0.0
os: linux
files:
  - source: /
    estination: /home/ec2-user/dj-app # 경로
    overwrite: yes
permissions:
  - object: /home/ec2-user/dj-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user