spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 123123 # KAKAO-REST-API-KEY
            client-secret: 34324234 # 클라이언트 시크릿 기능 활성화 후 사용
            redirect-uri: "{baseUrl}/login/oauth2/kakao" # http://localhost:8080/login/oauth2/kakao
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile # profile_image, profile_nickname를 포함한다.
              # - account_email

