server:
  port: 8080

spring:
  profiles:
    include:
      - db # db 설정
      - oauth2 # oauth2 설정
  mvc:
    # enable NoHandlerFoundException
    # throw-exception-if-no-handler-found: true
  #web:
    #resources:
      # disable spring's default resources/static directory path setting
      # disabled for use NoHandlerFoundException
      # add-mappings: false


#QueryLoggin
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: trace

