server:
  port: 8080

spring:
  profiles:
    include:
      - db # db 설정
      - oauth2 # oauth2 설정


logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
#QueryLoggin
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: trace

