
name: Deploy SpringBoot Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: CheckOut
    - uses: actions/checkout@v2
    
    - name: 자바 JDK 8 설치
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: gradlew 권한 부여
      run: chmod +x gradlew
      
    - name: Gradle Build
      run: ./gradlew build
    
    - name: 압축 시작.
      run: zip -qq -r ./we-are-dj-server.zip .
      shell: bash

